config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/recent', to: 'static_pages#recent', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {email.downcase!}
  before_create :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  validates :password, length: {minimum: 6}


  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_to user
    else
      flash[:danger] = "Invalid user/password combination"
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact

  end

  def recent

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "Добро пожаловать на Like N Strike!!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title (page_title)
    base_title = "This is our awesome app"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for (user, options = {size: 50})
    gravatar_new_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_new_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    (c) by Stepan Fedorov
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">

  <div class = "container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">likenstrike.me</a>
    </div>
    <div class="navbar-collapse collapse" style="height: auto;">
    <%#= link_to "likenstrike.me", '#', id: "logo" %>
    <ul class ="nav navbar-nav">
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Recent Bets",    recent_path %></li>
      <% if signed_in? %>
          <li><%= link_to "Users", '#'%>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            <ul>
          </li>
          <% else %>

      <li><%= link_to "Sign In", signin_path %></li>
          <%end%>

    </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= render 'shared/google_analytics' %>
</head>
<body>
  <%= render 'layouts/header'%>
<div class = "navbar-wrapper">
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer'%>
  <%= debug(params) if Rails.env.development? %>
</div>
</div>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_google_analytics.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-49960457-1', 'likenstrike.herokuapp.com');
    ga('send', 'pageview');

</script>

app/views/static_pages/about.html.erb
<%provide(:title,'About')%>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<%provide(:title,'Contact')%>
<h1>Contact Info</h1>

<p>
  Из искры да разгорится пламя!
</p>

app/views/static_pages/help.html.erb
<%provide(:title,'Help')%>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Добро пожаловать на Likenstrike.Me</h1>

<h2>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
<div>

app/views/static_pages/recent.html.erb
<%provide(:title,'Recent Bets')%>
<h1>Recent Bets</h1>
<p>
  <div class = "container container-width cont-paddings-small">
  <div class="row row-centered">
    <div class ="center col-md-6 col-sm-6 col-paddings-small" >

      <div class = "jumbotron red-jumbo jumbo-bet">

        <div class = "row">
        Я прыгну с парашютом если наберу
        </div>

        <div class = "row like-bar-row">
          <div class = "container like-bar">
            1.5k Лайков
          </div>
        </div>
      </div>
    </div>

    <div class ="center col-md-6 col-sm-6 col-paddings-small">
      <div class = "jumbotron purple-jumbo jumbo-bet">
        <div class = "row">
          Я прыгну с парашютом если наберу
        </div>

        <div class = "row like-bar-row">
          <div class = "container like-bar">
            1.5k Лайков
          </div>
        </div>
      </div>
    </div>


  </div>
    <div class="row row-centered">
      <div class ="center col-md-6 col-sm-6 col-paddings-small">
        <div class = "jumbotron green-jumbo jumbo-bet">
          <div class = "row">
            Я прыгну с парашютом если наберу
          </div>

          <div class = "row like-bar-row">
            <div class = "container like-bar">
              10k Лайков
            </div>
          </div>
        </div>
      </div>
      <div class ="center col-md-6 col-sm-6 col-paddings-small">
        <div class = "jumbotron blue-jumbo jumbo-bet">
          <div class = "row">
            Я прыгну с парашютом если наберу
          </div>

          <div class = "row like-bar-row">
            <div class = "container like-bar">
              300 Лайков
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-sm-6 col-sm-offset-3 col-md-offset-3">
    <div class = "form">
    <%= form_for(@user) do |f| %>

        <%= render 'shared/error_messages' %>

        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder:"Enter your Name" %>
        </div>

        <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", placeholder:"Enter your Email"%>
        </div>

        <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder:"Password" %>
        </div>

        <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder:"Repeat password" %>
        </div>


       <%= f.submit "Create my account", class: "btn btn-primary" %>

     </div>

    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-6">
    <section>
        <h1>
            <%= gravatar_for @user, size: 40 %>
            <%= @user.name %>
        </h1>
    </section>
  </aside>
</div>